//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryFull
    {
        public int Код { get; set; }
        public string ФИО { get; set; }
        public string Название { get; set; }
        public string ФиоСотрудника { get; set; }
        public Nullable<int> Количества { get; set; }
        public System.DateTime ДатаВыдачи { get; set; }
        public Nullable<System.DateTime> ДатаСдачи { get; set; }
    }
}
