//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ВыдачаИнвентаря
    {
        public int Код { get; set; }
        public int КодЗаселения { get; set; }
        public int КодИнвентаря { get; set; }
        public int КодСотрудника { get; set; }
        public System.DateTime ДатаВыдачи { get; set; }
        public Nullable<System.DateTime> ДатаСдачи { get; set; }
    
        public virtual Заселение Заселение { get; set; }
        public virtual Инвентарь Инвентарь { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
