//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оплата
    {
        public int Код { get; set; }
        public int КодЗаселения { get; set; }
        public System.DateTime Дата { get; set; }
        public int Сумма { get; set; }
    
        public virtual Заселение Заселение { get; set; }
    }
}
